require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe LoanedBooksController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # LoanedBook. As you add validations to LoanedBook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LoanedBooksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all loaned_books as @loaned_books" do
      loaned_book = LoanedBook.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:loaned_books)).to eq([loaned_book])
    end
  end

  describe "GET #show" do
    it "assigns the requested loaned_book as @loaned_book" do
      loaned_book = LoanedBook.create! valid_attributes
      get :show, {:id => loaned_book.to_param}, valid_session
      expect(assigns(:loaned_book)).to eq(loaned_book)
    end
  end

  describe "GET #new" do
    it "assigns a new loaned_book as @loaned_book" do
      get :new, {}, valid_session
      expect(assigns(:loaned_book)).to be_a_new(LoanedBook)
    end
  end

  describe "GET #edit" do
    it "assigns the requested loaned_book as @loaned_book" do
      loaned_book = LoanedBook.create! valid_attributes
      get :edit, {:id => loaned_book.to_param}, valid_session
      expect(assigns(:loaned_book)).to eq(loaned_book)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new LoanedBook" do
        expect {
          post :create, {:loaned_book => valid_attributes}, valid_session
        }.to change(LoanedBook, :count).by(1)
      end

      it "assigns a newly created loaned_book as @loaned_book" do
        post :create, {:loaned_book => valid_attributes}, valid_session
        expect(assigns(:loaned_book)).to be_a(LoanedBook)
        expect(assigns(:loaned_book)).to be_persisted
      end

      it "redirects to the created loaned_book" do
        post :create, {:loaned_book => valid_attributes}, valid_session
        expect(response).to redirect_to(LoanedBook.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved loaned_book as @loaned_book" do
        post :create, {:loaned_book => invalid_attributes}, valid_session
        expect(assigns(:loaned_book)).to be_a_new(LoanedBook)
      end

      it "re-renders the 'new' template" do
        post :create, {:loaned_book => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested loaned_book" do
        loaned_book = LoanedBook.create! valid_attributes
        put :update, {:id => loaned_book.to_param, :loaned_book => new_attributes}, valid_session
        loaned_book.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested loaned_book as @loaned_book" do
        loaned_book = LoanedBook.create! valid_attributes
        put :update, {:id => loaned_book.to_param, :loaned_book => valid_attributes}, valid_session
        expect(assigns(:loaned_book)).to eq(loaned_book)
      end

      it "redirects to the loaned_book" do
        loaned_book = LoanedBook.create! valid_attributes
        put :update, {:id => loaned_book.to_param, :loaned_book => valid_attributes}, valid_session
        expect(response).to redirect_to(loaned_book)
      end
    end

    context "with invalid params" do
      it "assigns the loaned_book as @loaned_book" do
        loaned_book = LoanedBook.create! valid_attributes
        put :update, {:id => loaned_book.to_param, :loaned_book => invalid_attributes}, valid_session
        expect(assigns(:loaned_book)).to eq(loaned_book)
      end

      it "re-renders the 'edit' template" do
        loaned_book = LoanedBook.create! valid_attributes
        put :update, {:id => loaned_book.to_param, :loaned_book => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested loaned_book" do
      loaned_book = LoanedBook.create! valid_attributes
      expect {
        delete :destroy, {:id => loaned_book.to_param}, valid_session
      }.to change(LoanedBook, :count).by(-1)
    end

    it "redirects to the loaned_books list" do
      loaned_book = LoanedBook.create! valid_attributes
      delete :destroy, {:id => loaned_book.to_param}, valid_session
      expect(response).to redirect_to(loaned_books_url)
    end
  end

end
